version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies"
      - mvn clean install -DskipTests=true -B -V
  build:
    commands:
      - echo "Packaging the Spring Boot application"
      - mvn package -Passembly-zip -DskipTests=true -B
      - cp target/ExpenseManagerBackend-1.0-SNAPSHOT-lambda-package.zip ExpenseManagerBackend-1.0-SNAPSHOT-lambda-package.zip
  post_build:
    commands:
      - echo "Uploading artifact to S3"
      - aws s3 cp ExpenseManagerBackend-1.0-SNAPSHOT-lambda-package.zip s3://spendwise-main/ExpenseManagerBackend-1.0-SNAPSHOT-lambda-package.zip
